# Generated by Django 6.0.1 on 2026-04-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('ore_volume', models.FloatField(help_text='Объём добытой руды, тонн')),
                ('operating_time', models.FloatField(help_text='Плановое время работы, часы')),
                ('downtime', models.FloatField(help_text='Время простоя, часы')),
                ('crew_size', models.IntegerField(help_text='Численность бригады')),
                ('fuel_consumption', models.FloatField(help_text='Расход топлива, литры')),
            ],
            options={
                'verbose_name': 'Производственные данные',
                'verbose_name_plural': 'Производственные данные',
            },
        ),
    ]
